@startuml
!include _style.iuml
|Гость|
start
:Открыть карточку номера;
:Указать даты заезда и выезда,\nчисло гостей;
|Web-приложение|
:Рассчитать стоимость\n(GET /api/rooms/{slug}/quote);
|Гость|
:Указать имя, телефон,\nкомментарий и промокод;
:Нажать кнопку бронирования;
|Web-приложение|
if (Вход выполнен и почта\nподтверждена?) then (нет)
  :Сообщить, что нужно войти\nили подтвердить почту;
  stop
else (да)
endif
if (Номер доступен, гостей не больше\nвместимости, даты свободны, заявок\nна рассмотрении меньше трёх?) then (нет)
  :Показать причину отказа;
  stop
else (да)
endif
:Проверить промокод\nи рассчитать скидку;
:Создать заявку\nв статусе pending;
if (Клиент заблокирован?) then (да)
  :Отклонить заявку\n(declined);
elseif (Сработало правило\nручной проверки?) then (да)
  :Оставить на рассмотрении,\nуведомить администратора;
else (нет)
  :Подтвердить (confirmed),\nсоздать задачи уборки;
endif
:Записать событие в журнал,\nотправить письмо гостю;
|Гость|
:Увидеть статус брони;
stop
@enduml
