@startuml
!include _style.iuml
|Пользователь|
start
repeat
  :Заполнить форму регистрации:\nимя, email, пароль, согласие\nна обработку персональных данных;
  |Web-приложение|
  :Проверить пароль: длина не менее\n15 символов, оценка zxcvbn;
repeat while (Данные некорректны?) is (да) not (нет)
if (Email уже зарегистрирован?) then (да)
  :Отправить письмо\n«аккаунт уже существует»;
else (нет)
  :Создать пользователя с ролью guest,\nсохранить хэш пароля Argon2;
  :Выдать токен и отправить письмо\nсо ссылкой подтверждения;
endif
:Показать сообщение\nо письме;
|Пользователь|
:Открыть ссылку из письма\nи подтвердить почту;
|Web-приложение|
:Погасить токен,\nотметить email_verified_at;
|Пользователь|
:Ввести email и пароль\nна странице входа;
|Web-приложение|
if (Пара email/пароль верна\nи аккаунт активен?) then (да)
  :Создать сессию,\nустановить httpOnly-cookie;
  :Открыть запрошенную страницу\nили личный кабинет;
else (нет)
  :Сообщить «Неверный\nemail или пароль»;
endif
stop
@enduml
