skinparam dpi 150
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam shadowing false
skinparam backgroundColor white
skinparam ArrowColor #333333
skinparam ActorBorderColor #333333
skinparam UsecaseBackgroundColor #FFFFFF
skinparam UsecaseBorderColor #333333
skinparam RectangleBorderColor #333333
skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #333333
skinparam ActivityDiamondBackgroundColor #FFFFFF
skinparam ActivityDiamondBorderColor #333333
skinparam SwimlaneBorderColor #666666
skinparam NodeBackgroundColor #F7F7F7
skinparam ComponentBackgroundColor #FFFFFF
skinparam DatabaseBackgroundColor #FFFFFF
skinparam CloudBackgroundColor #FFFFFF
